demoproj/demoproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
         path('movies/', include('movies.urls')),
         path('admin/', admin.site.urls),
]

demoproj/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'	

urlpatterns = [
	# /movies/
	path('', views.index, name='index'),
	# /movies/id  e.g. /movies/1
	path('<int:movie_id>/', views.show, name='show'),
]

demoproj/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
	# each class variable represents a database i.e. table field in the model
	title = models.CharField(max_length=200)
	director = models.CharField(max_length=30)
	release_date = models.DateTimeField('release date')
	genre = models.CharField(max_length=200)
	duration = models.FloatField()

def __str__(self):
	return self.title + " - " + self.director

demoproj/movies/views.py
from django.shortcuts import render
from .models import Movie
from django.http import Http404


def index(request):
	newest_movies = Movie.objects.order_by('-release_date')[:15]
	context = {'newest_movies': newest_movies}
	return render(request, 'movies/index.html', context)


def show(request, movie_id):
	try:
		movie = Movie.objects.get(pk=movie_id)
	except Movie.DoesNotExist:
		raise Http404("Movie does not exist")
	return render(request, 'movies/show.html', {'movie': movie})

demoproj/movies/templates/movies/index.html
<h1>Newest Movies</h1>
{% if newest_movies %}
<ul>
  {% for movie in newest_movies %}
  <li><a href="{% url 'movies:show' movie.id %}">{{ movie.title }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>There are no movies recorded.</p>
{% endif %}

demoproj/movies/templates/movies/show.html
<h2>{{movie.title}} Details</h2>
<table>
  <thead></thead>
  <tbody>
    <tr>
      <td><b>Director:</b></td>
      <td>{{movie.director}}</td>
    </tr>
    <tr>
      <td><b>Release date:</b></td>
      <td>{{movie.release_date}}</td>
    </tr>
    <tr>
      <td><b>Genre:</b></td>
      <td>{{movie.genre}}</td>
    </tr>
    <tr>
      <td><b>Duration (min):</b></td>
      <td>{{movie.duration}}</td>
    </tr>
  </tbody>
</table>